spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AulaRepository
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create